# Generated by Django 2.2.28 on 2022-12-09 05:53

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('cou_currency', models.CharField(max_length=20)),
                ('currency_symbol', models.CharField(max_length=20)),
                ('time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
